# Generated by Django 5.0.6 on 2024-06-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_APIApp', '0002_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
